---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gadgetbridge-sa
  namespace: gadgetbridge
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-sa
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-sa
  namespace: cicd
