all:
  children:
    gitea:
      hosts:
        gitea-vm:
          ansible_host: 10.0.0.54
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/homelab
          ansible_ssh_common_args: '-J proxmox'
    k8s_control:
      hosts:
    k8s_workers:
      hosts:
