name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible ansible-lint

      - name: Lint Ansible
        run: |
          ansible-lint ansible/site.yaml

  validate-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Format Check
        run: |
          cd terraform/environments/gitea
          terraform fmt -check -recursive
