---
- name: Apply common configuration
  hosts: all
  roles:
    - common

- name: Deploy Gitea
  hosts: gitea
  roles:
    - gitea

- name: Apply K8s prerequisites
  hosts: k8s
  roles:
    - k8s-prereqs